
package webSrc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileReaderWSService", targetNamespace = "http://FileReader/", wsdlLocation = "http://localhost:9000/FileReader?wsdl")
public class FileReaderWSService
    extends Service
{

    private final static URL FILEREADERWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILEREADERWSSERVICE_EXCEPTION;
    private final static QName FILEREADERWSSERVICE_QNAME = new QName("http://FileReader/", "FileReaderWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/FileReader?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILEREADERWSSERVICE_WSDL_LOCATION = url;
        FILEREADERWSSERVICE_EXCEPTION = e;
    }

    public FileReaderWSService() {
        super(__getWsdlLocation(), FILEREADERWSSERVICE_QNAME);
    }

    public FileReaderWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILEREADERWSSERVICE_QNAME, features);
    }

    public FileReaderWSService(URL wsdlLocation) {
        super(wsdlLocation, FILEREADERWSSERVICE_QNAME);
    }

    public FileReaderWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILEREADERWSSERVICE_QNAME, features);
    }

    public FileReaderWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileReaderWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileReaderWS
     */
    @WebEndpoint(name = "FileReaderWSPort")
    public FileReaderWS getFileReaderWSPort() {
        return super.getPort(new QName("http://FileReader/", "FileReaderWSPort"), FileReaderWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileReaderWS
     */
    @WebEndpoint(name = "FileReaderWSPort")
    public FileReaderWS getFileReaderWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://FileReader/", "FileReaderWSPort"), FileReaderWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILEREADERWSSERVICE_EXCEPTION!= null) {
            throw FILEREADERWSSERVICE_EXCEPTION;
        }
        return FILEREADERWSSERVICE_WSDL_LOCATION;
    }

}
