
package webSrc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileReaderWS", targetNamespace = "http://FileReader/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileReaderWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readSample", targetNamespace = "http://FileReader/", className = "webSrc.ReadSample")
    @ResponseWrapper(localName = "readSampleResponse", targetNamespace = "http://FileReader/", className = "webSrc.ReadSampleResponse")
    @Action(input = "http://FileReader/FileReaderWS/readSampleRequest", output = "http://FileReader/FileReaderWS/readSampleResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://FileReader/FileReaderWS/readSample/Fault/IOException")
    })
    public String readSample(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

}
